version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - run:
          name: Install build tools
          command: |
            apt-get update
            apt-get install -y build-essential

      - checkout

      - run:
          name: Build and run C++ code
          command: |
            g++ -o test test.cpp
            ./test